# Generated by Django 3.0.3 on 2020-02-06 15:32

from django.db import migrations

#change the set up model 
class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='question_text',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
